#ifndef FLAGS_H
#define FLAGS_H

enum file_progress_e{
    
    FILEPROG_3_MUSIC_NOTE_TEXT = 0x3,
    FILEPROG_4_MUMBO_TOKEN_TEXT,
    FILEPROG_5_BLUE_EGG_TEXT,
    FILEPROG_6_RED_FEATHER_TEXT,
    FILEPROG_7_GOLD_FEATHER_TEXT,
    FILEPROG_8_ORANGE_TEXT,
    FILEPROG_9_GOLD_BULLION_TEXT,
    FILEPROG_A_HONEYCOMB_TEXT,
    FILEPROG_B_EMPTY_HONEYCOMB_TEXT,
    FILEPROG_C_EXTRA_LIFE_TEXT,
    FILEPROG_D_BEEHIVE_TEXT,
	FILEPROG_E_JINJO_TEXT,
    FILEPROG_F_HAS_TOUCHED_PIRAHANA_WATER,
	FILEPROG_10_HAS_TOUCHED_SAND_EEL_SAND,
    FILEPROG_11_HAS_MET_MUMBO, 
    FILEPROG_12_HAS_TRANSFORMED_BEFORE,
    FILEPROG_13, //something with xmas tree jiggy progress
    FILEPROG_14_HAS_TOUCHED_FP_ICY_WATER,
    FILEPROG_15_ENTER_MMM_TEXT,
    FILEPROG_16_STOOD_ON_JIGSAW_PODIUM,
    FILEPROG_17_HAS_HAD_ENOUGH_JIGSAW_PIECES,
    FILEPROG_18_MM_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_19_MMM_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_1A_TTC_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_1B_MET_YELLOW_FLIBBITS,
    FILEPROG_1C_RBB_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_1D_MMM_DINNING_ROOM_CUTSCENE,
    FILEPROG_1E_LAIR_GRATE_TO_BGS_PUZZLE_OPEN,
    FILEPROG_1F_CC_LOBBY_PIPE_1_RAISED,
    FILEPROG_20_CC_LOBBY_PIPE_2_RAISED,
    FILEPROG_21_CC_LOBBY_PIPE_3_RAISED,
    FILEPROG_22_WATER_SWITCH_1_PRESSED,
    FILEPROG_23_LAIR_WATER_LEVEL_1,
    FILEPROG_24_WATER_SWITCH_2_PRESSED,
    FILEPROG_25_LAIR_WATER_LEVEL_2,
    FILEPROG_26_WATER_SWITCH_3_PRESSED,
    FILEPROG_27_LAIR_WATER_LEVEL_3,

    FILEPROG_31_MM_OPEN = 0x31,
    FILEPROG_32_TTC_OPEN,
    FILEPROG_33_CC_OPEN,
    FILEPROG_34_BGS_OPEN,
    FILEPROG_35_FP_OPEN,
    FILEPROG_36_GV_OPEN,
    FILEPROG_37_MMM_OPEN,
    FILEPROG_38_RBB_OPEN,
    FILEPROG_39_CCW_OPEN,
    FILEPROG_3A_NOTE_DOOR_50_OPEN,
    FILEPROG_3B_NOTE_DOOR_180_OPEN,
    FILEPROG_3C_NOTE_DOOR_260_OPEN,
    FILEPROG_3D_NOTE_DOOR_350_OPEN,
    FILEPROG_3E_NOTE_DOOR_450_OPEN,
    FILEPROG_3F_NOTE_DOOR_640_OPEN,
    FILEPROG_40_NOTE_DOOR_765_OPEN,
    FILEPROG_41_NOTE_DOOR_810_OPEN,
    FILEPROG_42_NOTE_DOOR_828_OPEN,
    FILEPROG_43_NOTE_DOOR_846_OPEN,
    FILEPROG_44_NOTE_DOOR_864_OPEN,
    FILEPROG_45_NOTE_DOOR_882_OPEN,
    FILEPROG_46_CCW_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_47_FP_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_48_FP_WITCH_SWITCH_ADVENT_DOOR_OPEN,
    // {index=0x49, type="Prog", level=6, name="Pink Cauldron 1 Active"},
    // {index=0x4A, type="Prog", level=6, name="Pink Cauldron 2 Active"},
    // {index=0x4B, type="Prog", level=6, name="Green Cauldron 1 Active"},
    // {index=0x4C, type="Prog", level=6, name="Green Cauldron 2 Active"},
    // {index=0x4D, type="Prog", level=6, name="Red Cauldron 1 Active"},
    // {index=0x4E, type="Prog", level=6, name="Red Cauldron 2 Active"},
    // -- 0x4F - Unused Cauldron Pair?
    // -- 0x50 - Unused Cauldron Pair?
    // {index=0x51, type="Prog", level=6, name="Yellow Cauldron 1 Active"},
    // {index=0x52, type="Prog", level=6, name="Yellow Cauldron 2 Active"},
    FILEPROG_53_CCW_PUZZLE_PODIUM_SWITCH_PRESSED = 0x53,
    FILEPROG_54_CCW_PUZZLE_PODIUM_ACTIVE,
    FILEPROG_55_FF_BK_SQUARE_INSTRUCTIONS,
    FILEPROG_56_FF_PICTURE_SQUARE_INSTRUCTIONS,
    FILEPROG_57_FF_MUSIC_SQAURE_INSTRUCTIONS,
    FILEPROG_58_FF_MINIGAME_SQAURE_INSTRUCTIONS,
    FILEPROG_59_FF_GRUNTY_SQAURE_INSTRUCTIONS,
    FILEPROG_5A_FF_DEATH_SQAURE_INSTRUCTIONS,
    FILEPROG_5B_FF_JOKER_SQAURE_INSTRUCTIONS,
    FILEPROG_5C_FF_PATTERN_SET,
    FILEPROG_5D_MM_PUZZLE_PIECES_PLACED  = 0x5D, //1 bit
    FILEPROG_5E_TCC_PUZZLE_PIECES_PLACED = 0x5E, //2 bit
    FILEPROG_60_CC_PUZZLE_PIECES_PLACED  = 0x60, //3 bit
    FILEPROG_63_BGS_PUZZLE_PIECES_PLACED = 0x63, //3 bit
    FILEPROG_66_FP_PUZZLE_PIECES_PLACED  = 0x66, //4 bit
    FILEPROG_6A_GV_PUZZLE_PIECES_PLACED  = 0x6A, //4 bit
    FILEPROG_6E_MMM_PUZZLE_PIECES_PLACED = 0x6E, //4 bit
    FILEPROG_72_RBB_PUZZLE_PIECES_PLACED = 0x72, //4 bit
    FILEPROG_76_CCW_PUZZLE_PIECES_PLACED = 0x76, //4 bit
    FILEPROG_7A_DOG_PUZZLE_PIECES_PLACED = 0x7A, //5 bit
    FILEPROG_7F_DOUBLE_HEALTH_PUZZLE_PIECES_PLACED = 0x7F, //3 bit
    // {index=0x82, unknown}
    FILEPROG_82_MET_TWINKLIES = 0x82,
    FILEPROG_83_MAGIC_GET_WEAK_TEXT,
    FILEPROG_84_MAGIC_ALL_GONE_TEXT,
	// {index=0x85, type="Prog", level=6, name="Lair Crypt Gate Open"},
    FILEPROG_86_HAS_TOUCHED_MMM_THORN_HEDGE = 0x86,

    FILEPROG_88_TRIED_LOGGO_AS_BEAR = 0x88,
    FILEPROG_89_ENTERED_LOGGO_AS_PUMPKIN,
    FILEPROG_8A_EXITED_LOGGO,
    FILEPROG_8B_CCW_SPRING_OPEN,
    FILEPROG_8C_CCW_SUMMER_OPEN,
    FILEPROG_8D_CCW_AUTUMN_OPEN,
    FILEPROG_8E_CCW_WINTER_OPEN,
    FILEPROG_8F_MET_BEE_INFESTED_BEEHIVE,
    FILEPROG_90_PAID_TERMITE_COST,
    FILEPROG_91_PAID_PUMPKIN_COST,
    FILEPROG_92_PAID_WALRUS_COST,
    FILEPROG_93_PAID_CROC_COST,
    FILEPROG_94_PAID_BEE_COST,

	FILEPROG_96_MET_BRENTILDA = 0x96,
    FILEPROG_97_ENTERED_LAIR_TEXT,
	FILEPROG_98_EXITED_LEVEL_TEXT,
    FILEPROG_99_PAST_50_NOTE_DOOR_TEXT,
    FILEPROG_9A_CC_WITCH_SWITCH_PRESSED,
	FILEPROG_9B_LAIR_CC_WITCH_SWITCH_EYES_ACTIVE,
    FILEPROG_9C_LAIR_CC_WITCH_SWITCH_LEFT_EYE_PRESSED,
	FILEPROG_9D_LAIR_CC_WITCH_SWITCH_RIGHT_EYE_PRESSED,
    FILEPROG_9E_CRYPT_COFFIN_LID_OPEN,
    FILEPROG_9F_BGS_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_A0_GV_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_A1_STATUE_HAT_OPEN,
    FILEPROG_A2_GV_LOBBY_COFFIN_OPEN,
    FILEPROG_A3_GV_SNS_SWITCH_PRESSED,
    FILEPROG_A4_GV_SNS_SARCOPHAGUS_OPEN,
    //crypt gate open?
    FILEPROG_A6_FURNACE_FUN_COMPLETE = 0xA6,
    FILEPROG_A7_NEAR_PUZZLE_PODIUM_TEXT,
    FILEPROG_A8_HAS_DIED,
    FILEPROG_A9_HAS_TOUCHED_RBB_OVEN,
    FILEPROG_AA_HAS_TOUCHED_CCW_BRAMBLE_FIELD,
    FILEPROG_AB_SWIM_OILY_WATER,
    FILEPROG_AC_DIVE_OILY_WATER,
    FILEPROG_AD_CHEATO_BLUEEGGS_UNLOCKED,
    FILEPROG_AE_CHEATO_REDFEATHERS_UNLOCKED,
    FILEPROG_AF_CHEATO_GOLDFEATHERS_UNLOCKED,
    FILEPROG_B0_HAS_ENTERED_MM,
    FILEPROG_B1_HAS_ENTERED_BGS,
    FILEPROG_B2_HAS_ENTERED_TTC,
    FILEPROG_B3_HAS_ENTERED_GV,
    FILEPROG_B4_HAS_ENTERED_RBB,
    FILEPROG_B5_HAS_ENTERED_CCW,
    FILEPROG_B6_HAS_ENTERED_FP,
    FILEPROG_B7_HAS_ENTERED_MMM,
    FILEPROG_B8_HAS_ENTERED_CC,
    FILEPROG_B9_DOUBLE_HEALTH,
    FILEPROG_BA_HAS_SEEN_TREX_TEXT,
    FILEPROG_BB_MUMBO_MISTAKE_INDEX, //2 bits
    FILEPROG_BD_ENTER_LAIR_CUTSCENE = 0xBD,
    FILEPROG_BE_CHEATO_BLUEEGGS,
    FILEPROG_BF_CHEATO_REDFEATHERS,
    FILEPROG_C0_CHEATO_GOLDFEATHERS,
    FILEPROG_C1_BADDIES_ESCAPE_TEXT,
    FILEPROG_C2_GRATE_TO_RBB_PUZZLE_OPEN,
    FILEPROG_C3_ICE_BALL_TO_CHEATO_BROKEN,
    FILEPROG_C4_STATUE_EYE_BROKEN,
    FILEPROG_C5_RAREWARE_BOX_BROKEN,
    FILEPROG_C6_LAIR_JUMP_PAD_SWITCH_PRESSED,
    FILEPROG_C7_LAIR_JUMP_PAD_ACTIVE,
    FILEPROG_C8_LAIR_BRICKWALL_TO_WADINGBOOTS_BROKEN,
    FILEPROG_C9_LAIR_BRICKWALL_TO_SHOCKJUMP_PAD_BROKEN,
    FILEPROG_CA_COBWEB_BLOCKING_PURPLE_CAULDRON_BROKEN,
    FILEPROG_CB_LAIR_COBWEB_OVER_FLIGHTPAD_BROKEN,
    FILEPROG_CC_LAIR_COBWEB_OVER_GREEN_CAULDRON_BROKEN,
    FILEPROG_CD_GRATE_TO_WATER_SWITCH_3_OPEN,
    FILEPROG_CE_GRATE_TO_MMM_PUZZLE_OPEN,
    FILEPROG_CF_HAS_ENTERED_FINAL_FIGHT,
    
    FILEPROG_D1_HAS_ACTIVATED_A_JINJO_STATUE_IN_FINAL_FIGHT = 0xD1,
    FILEPROG_D2_HAS_SPAWNED_A_JINJO_STATUE_IN_FINAL_FIGHT,
    FILEPROG_D3_FF_PATTERN, //8 bit


	// {index=0xDB, unknown},
    FILEPROG_DB_SKIPPED_TUTORIAL = 0xDB,
    FILEPROG_DC_HAS_HAD_ENOUGH_TOKENS_BEFORE,
    FILEPROG_DD_HAS_TOUCHED_ICY_WATER,
    FILEPROG_DE_USED_ALL_YOUR_PUZZLE_PIECES,
    FILEPROG_DF_CAN_REMOVE_ALL_PUZZLE_PIECES,
    FILEPROG_E0_CAN_PLACE_ALL_PUZZLE_PIECES,

    FILEPROG_E2_DOOR_OF_GRUNTY_OPEN = 0xE2,
    FILEPROG_E3_CCW_FLOWER_SPRING,
    FILEPROG_E4_CCW_FLOWER_SUMMER,
    FILEPROG_E5_CCW_FLOWER_AUTUMN,
    FILEPROG_E6_SPRING_EYRIE_HATCHED,
    FILEPROG_E7_SUMMER_EYRIE_FED,
    FILEPROG_E8_AUTMN_EYRIE_FED,
    FILEPROG_E9_TALKED_TO_BRENTILDA_1,
    FILEPROG_EA_TALKED_TO_BRENTILDA_2,
    FILEPROG_EB_TALKED_TO_BRENTILDA_3,
    FILEPROG_EC_TALKED_TO_BRENTILDA_4,
    FILEPROG_ED_TALKED_TO_BRENTILDA_5,
    FILEPROG_EE_TALKED_TO_BRENTILDA_6,
    FILEPROG_EF_TALKED_TO_BRENTILDA_7,
    FILEPROG_F0_TALKED_TO_BRENTILDA_8,
    FILEPROG_F1_TALKED_TO_BRENTILDA_9,
    FILEPROG_F2_TALKED_TO_BRENTILDA_10,
    FILEPROG_F3_MET_DINGPOT,
    FILEPROG_F4_ENTER_FF_CUTSCENE,
    FILEPROG_F5_COMPLETED_A_WARP_CAULDRON_SET,
    FILEPROG_F6_SEEN_DOOR_OF_GRUNTY_PUZZLE_PODIUM,
    FILEPROG_F7_HAS_TRANSFORMED_IN_CRYPT,
	FILEPROG_F8_KING_SANDYBUTT_PYRAMID_STATE = 0xF8, //2bit
	// FILEPROG_F8_KING_SANDYBUTT_PYRAMID_STATE = 0xF9, //2bit

	FILEPROG_FC_DEFEAT_GRUNTY = 0xFC,
    FILEPROG_FD_CHEATCODES_ENTERED //2 bit
};

enum unkflags_1{
    UNKFLAGS1_6_HAS_SEEN_BOSS_BOOM_BOX_FF_MINIGAME = 0x6,
    UNKFLAGS1_7_HAS_SEEN_VILE_FF_MINIGAME,
    UNKFLAGS1_8_HAS_SEEN_MATCHING_PYRAMID_FF_MINIGAME,
    UNKFLAGS1_9_HAS_SEEN_ZUBBAS_FF_MINIGAME,
    UNKFLAGS1_A_HAS_SEEN_TIPTUP_FF_MINIGAME,
    UNKFLAGS1_B_HAS_SEEN_SANDCASTLE_FF_MINIGAME,

    UNKFLAGS1_1F_IN_CHARACTER_PARADE = 0x1F,
    UNKFLAGS1_20_BEGIN_CHARACTER_PARADE,

    UNKFLAGS1_73_SANDCASTLE_INFINITE_LIVES = 0x73,
    UNKFLAGS1_74_SANDCASTLE_INFINITE_EGGS,
    UNKFLAGS1_75_SANDCASTLE_INFINITE_RED_FEATHERS,
    UNKFLAGS1_76_SANDCASTLE_INFINITE_GOLD_FEATHERS,

    UNKFLAGS1_78_SANDCASTLE_NO_BONUS = 0x78,

    UNKFLAGS1_7F_SANDCASTLE_OPEN_CC = 0x7F,

    UNKFLAGS1_84_SANDCASTLE_OPEN_BGS = 0x84,

    UNKFLAGS1_86_SANDCASTLE_SHOCKSPRING_JUMP_UNLOCKED = 0x86,
    UNKFLAGS1_87_SANDCASTLE_OPEN_GV,//	0X87

    UNKFLAGS1_8A_SANDCASTLE_FLIGHT_UNLOCKED = 0x8A,//	0X8A
    UNKFLAGS1_8B_SANDCASTLE_OPEN_FP,//	0X8B
    UNKFLAGS1_8C_SANDCASTLE_OPEN_MMM,//	0X8C
    UNKFLAGS1_8D_SANDCASTLE_REMOVE_CRYPT_GATE,//	0X8D
    UNKFLAGS1_8E_SANDCASTLE_REMOVE_CRYPT_COFFIN_LID,//	0X8E
    UNKFLAGS1_8F_SANDCASTLE_REMOVE_GRATE_NEAR_WATER_SWITCH,//	0X8F
    UNKFLAGS1_90_SANDCASTLE_OPEN_RBB,

    UNKFLAGS1_93_SANDCASTLE_OPEN_CCW = 0x93,
    UNKFLAGS1_94_SANDCASTLE_INFINITE_HEALTH,//	0X94
    UNKFLAGS1_95_SANDCASTLE_INFINTE_MUMBO_TOKENS,//	0X95
    UNKFLAGS1_96_SANDCASTLE_INFINITE_AIR,//	0X96
    UNKFLAGS1_97_SANDCASTLE_BOTTLES_BONUS_1,//	0X97
    UNKFLAGS1_98_SANDCASTLE_BOTTLES_BONUS_2,//	0X98
    UNKFLAGS1_99_SANDCASTLE_BOTTLES_BONUS_3,//	0X99
    UNKFLAGS1_9A_SANDCASTLE_BOTTLES_BONUS_4,//	0X9A
    UNKFLAGS1_9B_SANDCASTLE_BOTTLES_BONUS_5,//	0X9B
    UNKFLAGS1_9C_SANDCASTLE_BOTTLES_BONUS_6,//	0X9C
    UNKFLAGS1_9D_SANDCASTLE_WISHY_WASHY,//	0X9D

    UNKFLAGS1_C0_BEGIN_FINAL_CHARACTER_PARADE = 0xC0,
    UNKFLAGS1_C1_IN_FINAL_CHARACTER_PARADE
};

enum level_flags_e
{
    LEVEL_FLAG_0_CC_TOKEN_TOOTH_OPEN = 0,
    LEVEL_FLAG_1_CC_JIGGY_TOOTH_OPEN = 1
};

#endif
