#ifndef FLAGS_H
#define FLAGS_H

enum file_progress_e{
    
    FILEPROG_3_MUSIC_NOTE_TEXT = 0x3,
    FILEPROG_4_MUMBO_TOKEN_TEXT,
    FILEPROG_5_BLUE_EGG_TEXT,
    FILEPROG_6_RED_FEATHER_TEXT,
    FILEPROG_7_GOLD_FEATHER_TEXT,
    FILEPROG_8_ORANGE_TEXT,
    FILEPROG_9_GOLD_BULLION_TEXT,
    FILEPROG_A_HONEYCOMB_TEXT,
    FILEPROG_B_EMPTY_HONEYCOMB_TEXT,
    FILEPROG_C_EXTRA_LIFE_TEXT,
    FILEPROG_D_BEEHIVE_TEXT,
	FILEPROG_E_JINJO_TEXT,
    FILEPROG_F_HAS_TOUCHED_PIRAHANA_WATER,
	FILEPROG_10_HAS_TOUCHED_SAND_EEL_SAND,
    FILEPROG_11_HAS_MET_MUMBO, 
    FILEPROG_12_HAS_TRANSFORMED_BEFORE,
    FILEPROG_13, //something with xmas tree jiggy progress
    FILEPROG_14_HAS_TOUCHED_FP_ICY_WATER,
    FILEPROG_15_ENTER_MMM_TEXT,
    FILEPROG_16_STOOD_ON_JIGSAW_PODIUM,
    FILEPROG_17_HAS_HAD_ENOUGH_JIGSAW_PIECES,
    FILEPROG_18_MM_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_19_MMM_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_1A_TTC_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_1B_MET_YELLOW_FLIBBITS,
    FILEPROG_1C_RBB_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_1D_MMM_DINNING_ROOM_CUTSCENE,
    FILEPROG_1E_LAIR_GRATE_TO_BGS_PUZZLE_OPEN,
    FILEPROG_1F_CC_LOBBY_PIPE_1_RAISED,
    FILEPROG_20_CC_LOBBY_PIPE_2_RAISED,
    FILEPROG_21_CC_LOBBY_PIPE_3_RAISED,
    FILEPROG_22_WATER_SWITCH_1_PRESSED,
    FILEPROG_23_LAIR_WATER_LEVEL_1,
    FILEPROG_24_WATER_SWITCH_2_PRESSED,
    FILEPROG_25_LAIR_WATER_LEVEL_2,
    FILEPROG_26_WATER_SWITCH_3_PRESSED,
    FILEPROG_27_LAIR_WATER_LEVEL_3,

    FILEPROG_31_MM_OPEN = 0x31,
    FILEPROG_32_TTC_OPEN,
    FILEPROG_33_CC_OPEN,
    FILEPROG_34_BGS_OPEN,
    FILEPROG_35_FP_OPEN,
    FILEPROG_36_GV_OPEN,
    FILEPROG_37_MMM_OPEN,
    FILEPROG_38_RBB_OPEN,
    FILEPROG_39_CCW_OPEN,
    FILEPROG_3A_NOTE_DOOR_50_OPEN,
    FILEPROG_3B_NOTE_DOOR_180_OPEN,
    FILEPROG_3C_NOTE_DOOR_260_OPEN,
    FILEPROG_3D_NOTE_DOOR_350_OPEN,
    FILEPROG_3E_NOTE_DOOR_450_OPEN,
    FILEPROG_3F_NOTE_DOOR_640_OPEN,
    FILEPROG_40_NOTE_DOOR_765_OPEN,
    FILEPROG_41_NOTE_DOOR_810_OPEN,
    FILEPROG_42_NOTE_DOOR_828_OPEN,
    FILEPROG_43_NOTE_DOOR_846_OPEN,
    FILEPROG_44_NOTE_DOOR_864_OPEN,
    FILEPROG_45_NOTE_DOOR_882_OPEN,
    FILEPROG_46_CCW_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_47_FP_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_48_FP_WITCH_SWITCH_ADVENT_DOOR_OPEN,
    // {index=0x49, type="Prog", level=6, name="Pink Cauldron 1 Active"},
    // {index=0x4A, type="Prog", level=6, name="Pink Cauldron 2 Active"},
    // {index=0x4B, type="Prog", level=6, name="Green Cauldron 1 Active"},
    // {index=0x4C, type="Prog", level=6, name="Green Cauldron 2 Active"},
    // {index=0x4D, type="Prog", level=6, name="Red Cauldron 1 Active"},
    // {index=0x4E, type="Prog", level=6, name="Red Cauldron 2 Active"},
    // -- 0x4F - Unused Cauldron Pair?
    // -- 0x50 - Unused Cauldron Pair?
    // {index=0x51, type="Prog", level=6, name="Yellow Cauldron 1 Active"},
    // {index=0x52, type="Prog", level=6, name="Yellow Cauldron 2 Active"},
    FILEPROG_53_CCW_PUZZLE_PODIUM_SWITCH_PRESSED = 0x53,
    FILEPROG_54_CCW_PUZZLE_PODIUM_ACTIVE,
    FILEPROG_55_FF_BK_SQUARE_INSTRUCTIONS,
    FILEPROG_56_FF_PICTURE_SQUARE_INSTRUCTIONS,
    FILEPROG_57_FF_MUSIC_SQAURE_INSTRUCTIONS,
    FILEPROG_58_FF_MINIGAME_SQAURE_INSTRUCTIONS,
    FILEPROG_59_FF_GRUNTY_SQAURE_INSTRUCTIONS,
    FILEPROG_5A_FF_DEATH_SQAURE_INSTRUCTIONS,
    FILEPROG_5B_FF_JOKER_SQAURE_INSTRUCTIONS,
    FILEPROG_5C_FF_PATTERN_SET,
    FILEPROG_5D_MM_PUZZLE_PIECES_PLACED  = 0x5D, //1 bit
    FILEPROG_5E_TCC_PUZZLE_PIECES_PLACED = 0x5E, //2 bit
    FILEPROG_60_CC_PUZZLE_PIECES_PLACED  = 0x60, //3 bit
    FILEPROG_63_BGS_PUZZLE_PIECES_PLACED = 0x63, //3 bit
    FILEPROG_66_FP_PUZZLE_PIECES_PLACED  = 0x66, //4 bit
    FILEPROG_6A_GV_PUZZLE_PIECES_PLACED  = 0x6A, //4 bit
    FILEPROG_6E_MMM_PUZZLE_PIECES_PLACED = 0x6E, //4 bit
    FILEPROG_72_RBB_PUZZLE_PIECES_PLACED = 0x72, //4 bit
    FILEPROG_76_CCW_PUZZLE_PIECES_PLACED = 0x76, //4 bit
    FILEPROG_7A_DOG_PUZZLE_PIECES_PLACED = 0x7A, //5 bit
    FILEPROG_7F_DOUBLE_HEALTH_PUZZLE_PIECES_PLACED = 0x7F, //3 bit
    // {index=0x82, unknown}
    FILEPROG_82_MET_TWINKLIES = 0x82,
    FILEPROG_83_MAGIC_GET_WEAK_TEXT,
    FILEPROG_84_MAGIC_ALL_GONE_TEXT,
	// {index=0x85, type="Prog", level=6, name="Lair Crypt Gate Open"},
    FILEPROG_86_HAS_TOUCHED_MMM_THORN_HEDGE = 0x86,

    FILEPROG_88_TRIED_LOGGO_AS_BEAR = 0x88,
    FILEPROG_89_ENTERED_LOGGO_AS_PUMPKIN,
    FILEPROG_8A_EXITED_LOGGO,
    FILEPROG_8B_CCW_SPRING_OPEN,
    FILEPROG_8C_CCW_SUMMER_OPEN,
    FILEPROG_8D_CCW_AUTUMN_OPEN,
    FILEPROG_8E_CCW_WINTER_OPEN,
    FILEPROG_8F_MET_BEE_INFESTED_BEEHIVE,
    FILEPROG_90_PAID_TERMITE_COST,
    FILEPROG_91_PAID_PUMPKIN_COST,
    FILEPROG_92_PAID_WALRUS_COST,
    FILEPROG_93_PAID_CROC_COST,
    FILEPROG_94_PAID_BEE_COST,

	FILEPROG_96_MET_BRENTILDA = 0x96,
    FILEPROG_97_ENTERED_LAIR_TEXT,
	FILEPROG_98_EXITED_LEVEL_TEXT,
    FILEPROG_99_PAST_50_NOTE_DOOR_TEXT,
    FILEPROG_9A_CC_WITCH_SWITCH_PRESSED,
	FILEPROG_9B_LAIR_CC_WITCH_SWITCH_EYES_ACTIVE,
    FILEPROG_9C_LAIR_CC_WITCH_SWITCH_LEFT_EYE_PRESSED,
	FILEPROG_9D_LAIR_CC_WITCH_SWITCH_RIGHT_EYE_PRESSED,
    FILEPROG_9E_CRYPT_COFFIN_LID_OPEN,
    FILEPROG_9F_BGS_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_A0_GV_WITCH_SWITCH_JIGGY_PRESSED,
    FILEPROG_A1_STATUE_HAT_OPEN,
    FILEPROG_A2_GV_LOBBY_COFFIN_OPEN,
    FILEPROG_A3_GV_SNS_SWITCH_PRESSED,
    FILEPROG_A4_GV_SNS_SARCOPHAGUS_OPEN,
    //crypt gate open?
    FILEPROG_A6_FURNACE_FUN_COMPLETE = 0xA6,
    FILEPROG_A7_NEAR_PUZZLE_PODIUM_TEXT,
    FILEPROG_A8_HAS_DIED,
    FILEPROG_A9_HAS_TOUCHED_RBB_OVEN,
    FILEPROG_AA_HAS_TOUCHED_CCW_BRAMBLE_FIELD,
    FILEPROG_AB_SWIM_OILY_WATER,
    FILEPROG_AC_DIVE_OILY_WATER,
    FILEPROG_AD_CHEATO_BLUEEGGS_UNLOCKED,
    FILEPROG_AE_CHEATO_REDFEATHERS_UNLOCKED,
    FILEPROG_AF_CHEATO_GOLDFEATHERS_UNLOCKED,
    FILEPROG_B0_HAS_ENTERED_MM,
    FILEPROG_B1_HAS_ENTERED_BGS,
    FILEPROG_B2_HAS_ENTERED_TTC,
    FILEPROG_B3_HAS_ENTERED_GV,
    FILEPROG_B4_HAS_ENTERED_RBB,
    FILEPROG_B5_HAS_ENTERED_CCW,
    FILEPROG_B6_HAS_ENTERED_FP,
    FILEPROG_B7_HAS_ENTERED_MMM,
    FILEPROG_B8_HAS_ENTERED_CC,
    FILEPROG_B9_DOUBLE_HEALTH,
    FILEPROG_BA_HAS_SEEN_TREX_TEXT,
    FILEPROG_BB_MUMBO_MISTAKE_INDEX, //2 bits
    FILEPROG_BD_ENTER_LAIR_CUTSCENE = 0xBD,
    FILEPROG_BE_CHEATO_BLUEEGGS,
    FILEPROG_BF_CHEATO_REDFEATHERS,
    FILEPROG_C0_CHEATO_GOLDFEATHERS,
    FILEPROG_C1_BADDIES_ESCAPE_TEXT,
    FILEPROG_C2_GRATE_TO_RBB_PUZZLE_OPEN,
    FILEPROG_C3_ICE_BALL_TO_CHEATO_BROKEN,
    FILEPROG_C4_STATUE_EYE_BROKEN,
    FILEPROG_C5_RAREWARE_BOX_BROKEN,
    FILEPROG_C6_LAIR_JUMP_PAD_SWITCH_PRESSED,
    FILEPROG_C7_LAIR_JUMP_PAD_ACTIVE,
    FILEPROG_C8_LAIR_BRICKWALL_TO_WADINGBOOTS_BROKEN,
    FILEPROG_C9_LAIR_BRICKWALL_TO_SHOCKJUMP_PAD_BROKEN,
    FILEPROG_CA_COBWEB_BLOCKING_PURPLE_CAULDRON_BROKEN,
    FILEPROG_CB_LAIR_COBWEB_OVER_FLIGHTPAD_BROKEN,
    FILEPROG_CC_LAIR_COBWEB_OVER_GREEN_CAULDRON_BROKEN,
    FILEPROG_CD_GRATE_TO_WATER_SWITCH_3_OPEN,
    FILEPROG_CE_GRATE_TO_MMM_PUZZLE_OPEN,
    FILEPROG_CF_HAS_ENTERED_FINAL_FIGHT,
    
    FILEPROG_D1_HAS_ACTIVATED_A_JINJO_STATUE_IN_FINAL_FIGHT = 0xD1,
    FILEPROG_D2_HAS_SPAWNED_A_JINJO_STATUE_IN_FINAL_FIGHT,
    FILEPROG_D3_FF_PATTERN, //8 bit


	// {index=0xDB, unknown},
    FILEPROG_DB_SKIPPED_TUTORIAL = 0xDB,
    FILEPROG_DC_HAS_HAD_ENOUGH_TOKENS_BEFORE,
    FILEPROG_DD_HAS_TOUCHED_ICY_WATER,
    FILEPROG_DE_USED_ALL_YOUR_PUZZLE_PIECES,
    FILEPROG_DF_CAN_REMOVE_ALL_PUZZLE_PIECES,
    FILEPROG_E0_CAN_PLACE_ALL_PUZZLE_PIECES,

    FILEPROG_E2_DOOR_OF_GRUNTY_OPEN = 0xE2,
    FILEPROG_E3_CCW_FLOWER_SPRING,
    FILEPROG_E4_CCW_FLOWER_SUMMER,
    FILEPROG_E5_CCW_FLOWER_AUTUMN,
    FILEPROG_E6_SPRING_EYRIE_HATCHED,
    FILEPROG_E7_SUMMER_EYRIE_FED,
    FILEPROG_E8_AUTMN_EYRIE_FED,
    FILEPROG_E9_TALKED_TO_BRENTILDA_1,
    FILEPROG_EA_TALKED_TO_BRENTILDA_2,
    FILEPROG_EB_TALKED_TO_BRENTILDA_3,
    FILEPROG_EC_TALKED_TO_BRENTILDA_4,
    FILEPROG_ED_TALKED_TO_BRENTILDA_5,
    FILEPROG_EE_TALKED_TO_BRENTILDA_6,
    FILEPROG_EF_TALKED_TO_BRENTILDA_7,
    FILEPROG_F0_TALKED_TO_BRENTILDA_8,
    FILEPROG_F1_TALKED_TO_BRENTILDA_9,
    FILEPROG_F2_TALKED_TO_BRENTILDA_10,
    FILEPROG_F3_MET_DINGPOT,
    FILEPROG_F4_ENTER_FF_CUTSCENE,
    FILEPROG_F5_COMPLETED_A_WARP_CAULDRON_SET,
    FILEPROG_F6_SEEN_DOOR_OF_GRUNTY_PUZZLE_PODIUM,
    FILEPROG_F7_HAS_TRANSFORMED_IN_CRYPT,
	FILEPROG_F8_KING_SANDYBUTT_PYRAMID_STATE = 0xF8, //2bit
	// FILEPROG_F8_KING_SANDYBUTT_PYRAMID_STATE = 0xF9, //2bit

	FILEPROG_FC_DEFEAT_GRUNTY = 0xFC,
    FILEPROG_FD_CHEATCODES_ENTERED //2 bit
};

enum unkflags_1{
    UNKFLAGS1_6_HAS_SEEN_BOSS_BOOM_BOX_FF_MINIGAME = 0x6,
    UNKFLAGS1_7_HAS_SEEN_VILE_FF_MINIGAME,
    UNKFLAGS1_8_HAS_SEEN_MATCHING_PYRAMID_FF_MINIGAME,
    UNKFLAGS1_9_HAS_SEEN_ZUBBAS_FF_MINIGAME,
    UNKFLAGS1_A_HAS_SEEN_TIPTUP_FF_MINIGAME,
    UNKFLAGS1_B_HAS_SEEN_SANDCASTLE_FF_MINIGAME,

    UNKFLAGS1_1F_IN_CHARACTER_PARADE = 0x1F,
    UNKFLAGS1_20_BEGIN_CHARACTER_PARADE,

    UNKFLAGS1_73_SANDCASTLE_INFINITE_LIVES = 0x73,
    UNKFLAGS1_74_SANDCASTLE_INFINITE_EGGS,
    UNKFLAGS1_75_SANDCASTLE_INFINITE_RED_FEATHERS,
    UNKFLAGS1_76_SANDCASTLE_INFINITE_GOLD_FEATHERS,

    UNKFLAGS1_78_SANDCASTLE_NO_BONUS = 0x78,

    UNKFLAGS1_7F_SANDCASTLE_OPEN_CC = 0x7F,

    UNKFLAGS1_84_SANDCASTLE_OPEN_BGS = 0x84,

    UNKFLAGS1_86_SANDCASTLE_SHOCKSPRING_JUMP_UNLOCKED = 0x86,
    UNKFLAGS1_87_SANDCASTLE_OPEN_GV,//	0X87

    UNKFLAGS1_8A_SANDCASTLE_FLIGHT_UNLOCKED = 0x8A,//	0X8A
    UNKFLAGS1_8B_SANDCASTLE_OPEN_FP,//	0X8B
    UNKFLAGS1_8C_SANDCASTLE_OPEN_MMM,//	0X8C
    UNKFLAGS1_8D_SANDCASTLE_REMOVE_CRYPT_GATE,//	0X8D
    UNKFLAGS1_8E_SANDCASTLE_REMOVE_CRYPT_COFFIN_LID,//	0X8E
    UNKFLAGS1_8F_SANDCASTLE_REMOVE_GRATE_NEAR_WATER_SWITCH,//	0X8F
    UNKFLAGS1_90_SANDCASTLE_OPEN_RBB,

    UNKFLAGS1_93_SANDCASTLE_OPEN_CCW = 0x93,
    UNKFLAGS1_94_SANDCASTLE_INFINITE_HEALTH,//	0X94
    UNKFLAGS1_95_SANDCASTLE_INFINTE_MUMBO_TOKENS,//	0X95
    UNKFLAGS1_96_SANDCASTLE_INFINITE_AIR,//	0X96
    UNKFLAGS1_97_SANDCASTLE_BOTTLES_BONUS_1,//	0X97
    UNKFLAGS1_98_SANDCASTLE_BOTTLES_BONUS_2,//	0X98
    UNKFLAGS1_99_SANDCASTLE_BOTTLES_BONUS_3,//	0X99
    UNKFLAGS1_9A_SANDCASTLE_BOTTLES_BONUS_4,//	0X9A
    UNKFLAGS1_9B_SANDCASTLE_BOTTLES_BONUS_5,//	0X9B
    UNKFLAGS1_9C_SANDCASTLE_BOTTLES_BONUS_6,//	0X9C
    UNKFLAGS1_9D_SANDCASTLE_WISHY_WASHY,//	0X9D

    UNKFLAGS1_C0_BEGIN_FINAL_CHARACTER_PARADE = 0xC0,
    UNKFLAGS1_C1_IN_FINAL_CHARACTER_PARADE
};

enum level_flags_e
{
    LEVEL_FLAG_0_CC_TOKEN_TOOTH_OPEN = 0,
    LEVEL_FLAG_1_CC_JIGGY_TOOTH_OPEN = 1
};

enum volatile_flags_e {
    VOLATILE_FLAG_0_IN_FURNACE_FUN_QUIZ,
    VOLATILE_FLAG_1, // FF related
    VOLATILE_FLAG_2_FF_IN_MINIGAME,
    VOLATILE_FLAG_3, // FF related
    VOLATILE_FLAG_4, // FF related
    VOLATILE_FLAG_5_FF_MINIGAME_WON,
    VOLATILE_FLAG_6_HAS_SEEN_BOSS_BOOM_BOX_FF_MINIGAME,
    VOLATILE_FLAG_7_HAS_SEEN_VILE_FF_MINIGAME,
    VOLATILE_FLAG_8_HAS_SEEN_MATCHING_PYRAMID_FF_MINIGAME,
    VOLATILE_FLAG_9_HAS_SEEN_ZUBBAS_FF_MINIGAME,
    VOLATILE_FLAG_A_HAS_SEEN_TIPTUP_FF_MINIGAME,
    VOLATILE_FLAG_B_HAS_SEEN_SANDCASTLE_FF_MINIGAME,
    VOLATILE_FLAG_C_HAS_SEEN_SPRING_PAD,
    VOLATILE_FLAG_D_HAS_SEEN_FLIGHT_PAD,
    VOLATILE_FLAG_E, // related to chxmastree, GV waterctrl and RBB anchorswitch
    VOLATILE_FLAG_F_HAS_MEET_TURBO_SHOES,
    VOLATILE_FLAG_10_HAS_MEET_WADING_BOOTS,
    VOLATILE_FLAG_11, // unused
    VOLATILE_FLAG_12, // unused
    VOLATILE_FLAG_13_HAS_TRIGGERED_MUMBO_VACATION_TEXT,
    VOLATILE_FLAG_14, // unused
    VOLATILE_FLAG_15, // unused
    VOLATILE_FLAG_16, // related to beta function "return to lair"
    VOLATILE_FLAG_17, // 17 and 18: related to 50 note door and demo mode (?)
    VOLATILE_FLAG_18, // 17 and 18: related to 50 note door and demo mode (?)
    VOLATILE_FLAG_19_CURRENT_LEVEL_ID, // 4 bits for current level ID
    // VOLATILE_FLAG_1A to VOLATILE_FLAG_1C belong to VOLATILE_FLAG_19_CURRENT_LEVEL_ID
    VOLATILE_FLAG_1D = 0x1D, // unused
    VOLATILE_FLAG_1E, // related to warp cauldron or dingpot
    VOLATILE_FLAG_1F_IN_CHARACTER_PARADE,
    VOLATILE_FLAG_20_BEGIN_CHARACTER_PARADE,
    VOLATILE_FLAG_21, // related to FF
    VOLATILE_FLAG_22, // related to baddies escape text
    VOLATILE_FLAG_23_FINAL_BOSS_PHASE, // 3 bits for current phase in final boss fight
    // VOLATILE_FLAG_24 to VOLATILE_FLAG_25 belong to VOLATILE_FLAG_23_FINAL_BOSS_PHASE
    VOLATILE_FLAG_26_FF_GRUNTY_QUESTIONS = 0x26, // 60 bits FFQ Grunty Question related (two bits for every question)
    // VOLATILE_FLAG_27 to VOLATILE_FLAG_61 belong to VOLATILE_FLAG_26_FF_GRUNTY_QUESTIONS
    VOLATILE_FLAG_62_FF_GRUNTY_QUESTIONS_INITIALIZED = 0x62,
    VOLATILE_FLAG_63, // related to demo mode
    VOLATILE_FLAG_64, // related to demo mode
    VOLATILE_FLAG_65_CHEAT_ENTERED,
    VOLATILE_FLAG_66_SANDCASTLE_OPEN_DOOR_TWO,
    VOLATILE_FLAG_67_SANDCASTLE_OPEN_DOOR_THREE,
    VOLATILE_FLAG_68_SANDCASTLE_OPEN_DOOR_FOUR,
    VOLATILE_FLAG_69_SANDCASTLE_OPEN_DOOR_FIVE,
    VOLATILE_FLAG_6A_SANDCASTLE_OPEN_DOOR_SIX,
    VOLATILE_FLAG_6B_SANDCASTLE_OPEN_DOOR_SEVEN,
    VOLATILE_FLAG_6C_SANDCASTLE_PUZZLE_COMPLETE_CC,
    VOLATILE_FLAG_6D_SANDCASTLE_PUZZLE_COMPLETE_BGS,
    VOLATILE_FLAG_6E_SANDCASTLE_PUZZLE_COMPLETE_FP,
    VOLATILE_FLAG_6F_SANDCASTLE_PUZZLE_COMPLETE_GV,
    VOLATILE_FLAG_70_SANDCASTLE_PUZZLE_COMPLETE_MMM,
    VOLATILE_FLAG_71_SANDCASTLE_PUZZLE_COMPLETE_RBB,
    VOLATILE_FLAG_72_SANDCASTLE_PUZZLE_COMPLETE_CCC,
    VOLATILE_FLAG_73_SANDCASTLE_INFINITE_LIVES,
    VOLATILE_FLAG_74_SANDCASTLE_INFINITE_EGGS,
    VOLATILE_FLAG_75_SANDCASTLE_INFINITE_RED_FEATHERS,
    VOLATILE_FLAG_76_SANDCASTLE_INFINITE_GOLD_FEATHERS,
    VOLATILE_FLAG_77_SANDCASTLE_SET_HEALTH_TO_MAX, // unused
    VOLATILE_FLAG_78_SANDCASTLE_NO_BONUS,
    VOLATILE_FLAG_79, // unused
    VOLATILE_FLAG_7A, // unused
    VOLATILE_FLAG_7B, // unused
    VOLATILE_FLAG_7C, // unused
    VOLATILE_FLAG_7D_SANDCASTLE_RAISE_PIPES_TO_CC,
    VOLATILE_FLAG_7E_SANDCASTLE_RAISE_PIPE_TO_BRENTILDA,
    VOLATILE_FLAG_7F_SANDCASTLE_OPEN_CC,
    VOLATILE_FLAG_80_SANDCASTLE_REMOVE_GRILL_NEAR_BGS_JIGGY,
    VOLATILE_FLAG_81_SANDCASTLE_CCC_JIGGY_PODIUM,
    VOLATILE_FLAG_82_SANDCASTLE_REMOVE_GRILL_AND_HAT_FROM_STATUE,
    VOLATILE_FLAG_83_SANDCASTLE_REMOVE_ICE,
    VOLATILE_FLAG_84_SANDCASTLE_OPEN_BGS,
    VOLATILE_FLAG_85_SANDCASTLE_REMOVE_BREAKABLE_WALLS,
    VOLATILE_FLAG_86_SANDCASTLE_SHOCKSPRING_JUMP_UNLOCKED,
    VOLATILE_FLAG_87_SANDCASTLE_OPEN_GV,
    VOLATILE_FLAG_88_SANDCASTLE_REMOVE_WEBS,
    VOLATILE_FLAG_89_SANDCASTLE_REMOVE_GLASS_EYE,
    VOLATILE_FLAG_8A_SANDCASTLE_FLIGHT_UNLOCKED,
    VOLATILE_FLAG_8B_SANDCASTLE_OPEN_FP,
    VOLATILE_FLAG_8C_SANDCASTLE_OPEN_MMM,
    VOLATILE_FLAG_8D_SANDCASTLE_REMOVE_CRYPT_GATE,
    VOLATILE_FLAG_8E_SANDCASTLE_REMOVE_CRYPT_COFFIN_LID,
    VOLATILE_FLAG_8F_SANDCASTLE_REMOVE_GRATE_NEAR_WATER_SWITCH,
    VOLATILE_FLAG_90_SANDCASTLE_OPEN_RBB,
    VOLATILE_FLAG_91_SANDCASTLE_REMOVE_GRILL_NEAR_RBB_JIGGY,
    VOLATILE_FLAG_92_SANDCASTLE_REMOVE_TUNNEL_GRILL_NEAR_RBB_JIGGY,
    VOLATILE_FLAG_93_SANDCASTLE_OPEN_CCW,
    VOLATILE_FLAG_94_SANDCASTLE_INFINITE_HEALTH,
    VOLATILE_FLAG_95_SANDCASTLE_INFINTE_MUMBO_TOKENS,
    VOLATILE_FLAG_96_SANDCASTLE_INFINITE_AIR,
    VOLATILE_FLAG_97_SANDCASTLE_BOTTLES_BONUS_1,
    VOLATILE_FLAG_98_SANDCASTLE_BOTTLES_BONUS_2,
    VOLATILE_FLAG_99_SANDCASTLE_BOTTLES_BONUS_3,
    VOLATILE_FLAG_9A_SANDCASTLE_BOTTLES_BONUS_4,
    VOLATILE_FLAG_9B_SANDCASTLE_BOTTLES_BONUS_5,
    VOLATILE_FLAG_9C_SANDCASTLE_BOTTLES_BONUS_6,
    VOLATILE_FLAG_9D_SANDCASTLE_WISHY_WASHY,
    VOLATILE_FLAG_9E_BETA_OILY_SCUM,
    VOLATILE_FLAG_9F_BETA_DIVE_IN_ICY_WATER,
    VOLATILE_FLAG_A0_FF_FIRST_ANSWER_RIGHT,
    VOLATILE_FLAG_A1_FF_NEXT_ANSWER_RIGHT,
    VOLATILE_FLAG_A2_FF_GRUNTY_ANSWER_RIGHT,
    VOLATILE_FLAG_A3_FF_FIRST_ANSWER_WRONG,
    VOLATILE_FLAG_A4_FF_NEXT_ANSWER_WRONG,
    VOLATILE_FLAG_A5_FF_UNUSED,
    VOLATILE_FLAG_A6_FF_FOUND_HONEYCOMB,
    VOLATILE_FLAG_A7_FF_FOUND_EXTRALIFE,
    VOLATILE_FLAG_A8_FF_GOT_JOKER,
    VOLATILE_FLAG_A9_FF_USED_JOKER,
    VOLATILE_FLAG_AA_FF_LOW_HEALTH,
    VOLATILE_FLAG_AB_LAST_LIFE_ON_SKULL,
    VOLATILE_FLAG_AC_GV_TRAPDOOR_MISSED,
    VOLATILE_FLAG_AD_MMM_CHURCH_DOOR_MISSED,
    VOLATILE_FLAG_AE_BGS_WALKWAY_JIGGY_MISSED,
    VOLATILE_FLAG_AF_BGS_MAZE_JIGGY_MISSED,
    VOLATILE_FLAG_B0_NOT_ENOUGH_NOTES,
    VOLATILE_FLAG_B1, // unused
    VOLATILE_FLAG_B2, // ccw related
    VOLATILE_FLAG_B3, // boggy2 related
    VOLATILE_FLAG_B4, // fp related
    VOLATILE_FLAG_B5, // ccw related
    VOLATILE_FLAG_B6_WITCH_SWITCH_PRESSED_MM,
    VOLATILE_FLAG_B7_WITCH_SWITCH_PRESSED_MMM,
    VOLATILE_FLAG_B8_WITCH_SWITCH_PRESSED_TTC,
    VOLATILE_FLAG_B9_WITCH_SWITCH_PRESSED_RBB,
    VOLATILE_FLAG_BA_WITCH_SWITCH_PRESSED_CCW,
    VOLATILE_FLAG_BB_WITCH_SWITCH_PRESSED_FP,
    VOLATILE_FLAG_BC_WITCH_SWITCH_PRESSED_CC,
    VOLATILE_FLAG_BD_WITCH_SWITCH_PRESSED_BGS,
    VOLATILE_FLAG_BE_WITCH_SWITCH_PRESSED_GV,
    VOLATILE_FLAG_BF, // witch switch related
    VOLATILE_FLAG_C0_BEGIN_FINAL_CHARACTER_PARADE,
    VOLATILE_FLAG_C1_IN_FINAL_CHARACTER_PARADE,
    VOLATILE_FLAG_C2_NOBONUS_TEXT,
    VOLATILE_FLAG_C3, // SNS picture related
    VOLATILE_FLAG_C4_WOZZA_HIDE_IN_SNS_PARADE,
    VOLATILE_FLAG_C5_WISHYWASHYBANJO_TEXT,

    VOLATILE_FLAG_NUM_FLAGS
};

#endif
