#ifndef FLAGS_H
#define FLAGS_H

enum unkflags_1{
    UNKFLAGS1_6_HAS_SEEN_BOSS_BOOM_BOX_FF_MINIGAME = 0x6,
    UNKFLAGS1_7_HAS_SEEN_VILE_FF_MINIGAME,
    UNKFLAGS1_8_HAS_SEEN_MATCHING_PYRAMID_FF_MINIGAME,
    UNKFLAGS1_9_HAS_SEEN_ZUBBAS_FF_MINIGAME,
    UNKFLAGS1_A_HAS_SEEN_TIPTUP_FF_MINIGAME,
    UNKFLAGS1_B_HAS_SEEN_SANDCASTLE_FF_MINIGAME,

    UNKFLAGS1_1F_IN_CHARACTER_PARADE = 0x1F,
    UNKFLAGS1_20_BEGIN_CHARACTER_PARADE,

    UNKFLAGS1_73_SANDCASTLE_INFINITE_LIVES = 0x73,
    UNKFLAGS1_74_SANDCASTLE_INFINITE_EGGS,
    UNKFLAGS1_75_SANDCASTLE_INFINITE_RED_FEATHERS,
    UNKFLAGS1_76_SANDCASTLE_INFINITE_GOLD_FEATHERS,

    UNKFLAGS1_78_SANDCASTLE_NO_BONUS = 0x78,

    UNKFLAGS1_7F_SANDCASTLE_OPEN_CC = 0x7F,

    UNKFLAGS1_84_SANDCASTLE_OPEN_BGS = 0x84,

    UNKFLAGS1_86_SANDCASTLE_SHOCKSPRING_JUMP_UNLOCKED = 0x86,
    UNKFLAGS1_87_SANDCASTLE_OPEN_GV,//	0X87

    UNKFLAGS1_8A_SANDCASTLE_FLIGHT_UNLOCKED = 0x8A,//	0X8A
    UNKFLAGS1_8B_SANDCASTLE_OPEN_FP,//	0X8B
    UNKFLAGS1_8C_SANDCASTLE_OPEN_MMM,//	0X8C
    UNKFLAGS1_8D_SANDCASTLE_REMOVE_CRYPT_GATE,//	0X8D
    UNKFLAGS1_8E_SANDCASTLE_REMOVE_CRYPT_COFFIN_LID,//	0X8E
    UNKFLAGS1_8F_SANDCASTLE_REMOVE_GRATE_NEAR_WATER_SWITCH,//	0X8F
    UNKFLAGS1_90_SANDCASTLE_OPEN_RBB,

    UNKFLAGS1_93_SANDCASTLE_OPEN_CCW = 0x93,
    UNKFLAGS1_94_SANDCASTLE_INFINITE_HEALTH,//	0X94
    UNKFLAGS1_95_SANDCASTLE_INFINTE_MUMBO_TOKENS,//	0X95
    UNKFLAGS1_96_SANDCASTLE_INFINITE_AIR,//	0X96
    UNKFLAGS1_97_SANDCASTLE_BOTTLES_BONUS_1,//	0X97
    UNKFLAGS1_98_SANDCASTLE_BOTTLES_BONUS_2,//	0X98
    UNKFLAGS1_99_SANDCASTLE_BOTTLES_BONUS_3,//	0X99
    UNKFLAGS1_9A_SANDCASTLE_BOTTLES_BONUS_4,//	0X9A
    UNKFLAGS1_9B_SANDCASTLE_BOTTLES_BONUS_5,//	0X9B
    UNKFLAGS1_9C_SANDCASTLE_BOTTLES_BONUS_6,//	0X9C
    UNKFLAGS1_9D_SANDCASTLE_WISHY_WASHY,//	0X9D

    UNKFLAGS1_C0_BEGIN_FINAL_CHARACTER_PARADE = 0xC0,
    UNKFLAGS1_C1_IN_FINAL_CHARACTER_PARADE
};

#endif
