#ifndef ITEMS_H
#define ITEMS_H

enum item_e
{
    ITEM_0_HOURGLASS_TIMER = 0x0,
    ITEM_1_SKULL_HOURGLASS_TIMER,

    ITEM_3_PROPELLOR_TIMER = 0x3,

    ITEM_5_XMAS_TREE_TIMER = 0x5,
    ITEM_6_HOURGLASS,
    ITEM_7_SKULL_HOURGLASS,


    ITEM_9_PROPELLOR = 0x9,

    ITEM_B_XMAS_TREE = 0xb,
    ITEM_C_NOTE = 0xC,
    ITEM_D_EGGS,
    ITEM_E_JIGGY,
    ITEM_F_RED_FEATHER,
    ITEM_10_GOLD_FEATHER,

    ITEM_12_JINJOS = 0x12,
    ITEM_13_EMPTY_HONEYCOMB,
    ITEM_14_HEALTH,
    ITEM_15_HEALTH_TOTAL,
    ITEM_16_LIFE,
    ITEM_17_AIR,
    ITEM_18_GOLD_BULLIONS,
    ITEM_19_ORANGE,
    ITEM_1A_PLAYER_VILE_SCORE,
    ITEM_1B_VILE_VILE_SCORE,
    ITEM_1C_MUMBO_TOKEN,
    ITEM_1D_GRUMBLIE,
    ITEM_1E_YUMBLIE,
    ITEM_1F_GREEN_PRESENT,
    ITEM_20_BLUE_PRESENT,
    ITEM_21_RED_PRESENT,
    ITEM_22_CATERPILLAR,
    ITEM_23_ACORNS,
    ITEM_24_TWINKLY_SCORE,
    ITEM_25_MUMBO_TOKEN_TOTAL,
    ITEM_26_JIGGY_TOTAL,
    ITEM_27_JOKER_CARD,

    ITEM_2B_UNKNOWN = 0x2B //uses jiggy model
};

#endif
