#ifndef MARKER_H
#define MARKER_H

enum marker_e{
    MARKER_4_TERMITE = 0x4,
    MARKER_5_GRUBLIN,
    MARKER_6_MUMBO,
    MARKER_7_CONGA,

    MARKER_A_CHIMPY = 0xA,

    MARKER_C_ORANGE_PROJECTILE = 0xC,

    MARKER_11_WADING_BOOTS = 0x11,

    MARKER_13_SNIPPET = 0x13,

    MARKER_15_CLAM = 0x15,

    MARKER_28_CLANKER_SAWBLADE = 0x28,

    MARKER_2E_GRIMLET = 0x2E,

    MARKER_32_PLAYER_SHADOW = 0x32,
    MARKER_33_LEAKY,
    MARKER_34_CEMETARY_POT,

    MARKER_36_ORANGE_COLLECTIBLE = 0x36,
    MARKER_37_GOLD_BULLION,
    MARKER_38_TURBO_TALON_TRAINERS,
    MARKER_39_MUMBO_TOKEN,

    MARKER_3B_SCARF_SLED = 0x3B,
    MARKER_3C_RACE_SLED,

    MARKER_45_FLIGHT_PAD = 0x45,

    MARKER_48_NAPPER = 0x48,
    MARKER_49_MOTZHAND,
    MARKER_4A_CC_KEY,
    MARKER_4B_CC_SCREW,
    MARKER_4C_CLANKER_TOKEN_TOOTH_EXT,
    MARKER_4D_CLANKER_JIGGY_TOOTH_EXT,

    MARKER_51_MM_HUT = 0x51,
    MARKER_52_JIGGY,
    MARKER_53_EMPTY_HONEYCOMB,

    MARKER_55_HONEYCOMB = 0x55,

    MARKER_5A_JINJO_BLUE = 0x5A,
    MARKER_5B_JINJO_GREEN,
    MARKER_5C_JINJO_ORANGE,
    MARKER_5D_JINJO_PINK,
    MARKER_5E_JINJO_YELLOW,
    MARKER_5F_MUSIC_NOTE,
    MARKER_60_BLUE_EGG_COLLECTIBLE,
    MARKER_61_EXTRA_LIFE,
    MARKER_62_RED_ARROW,
    MARKER_63_RED_QUESTION_MARK,
    MARKER_64_RED_X,
    MARKER_65_SHRAPNEL,
    MARKER_66_ORANGE_PAD,
    MARKER_67_JUJU,
    MARKER_68_JIGSAW_DANCE,
    MARKER_69_CHUMP_FISH,
    MARKER_6A_GLOOP,
    MARKER_6B_GLOOPBUBBLE,
    MARKER_6C_TANKTUP,
    MARKER_6D_TANKTUP_LEG,
    MARKER_6E_PINK_EGG_LARGEST,

    MARKER_72_FIRE_SPARKLE = 0x72,

    MARKER_95_CHIMPY_STUMP = 0x95,
    MARKER_96_GRAVESTONE,
    MARKER_97_BOGGY_2,

    MARKER_99_TEEHEE = 0x99,

    MARKER_A3_BLUBBER = 0xA3,
    MARKER_A4_LOCKUP_SLOW,
    MARKER_A5_NIPPER,
    MARKER_A6_GRABBA,
    MARKER_A7_MAGIC_CARPET_1,
    MARKER_A8_GV_MAZE_SARCOPHAGUS,
    MARKER_A9_RUBEE,
    MARKER_AA_HISTUP,
    MARKER_AB_RUBEES_EGG_POT,

    MARKER_AD_SLAPPA = 0xAD,

    MARKER_AF_MAGIC_CARPET_SHADOW = 0xAF,
    MARKER_B0_MAGIC_CARPET_2,
    MARKER_B1_SIR_SLUSH,
    MARKER_B2_SNOWBALL,
    MARKER_B3_SIR_SLUSH_HAT,

    MARKER_B5_RED_FEATHER_COLLECTIBLE = 0xB5,

    MARKER_B7_TUTORIAL_BOTTLES = 0xB7,

    MARKER_B9_FP_SNOWMAN_BUTTON = 0xB9,
    MARKER_BA_XMAS_TREE,

    MARKER_BC_GOBI_1 = 0xBC,
    MARKER_BD_GOBI_ROPE,
    MARKER_BE_GOBI_ROCK,
    MARKER_BF_GOBI_2,
    MARKER_C0_TRUNKER,
    MARKER_C1_FLIBBIT_RED,
    MARKER_C2_BUZZBOMB,
    MARKER_C3_GOBI_3,
    MARKER_C4_YELLOW_FLIBBIT_CTRL,
    MARKER_C5_FLIBBIT_YELLOW,
    MARKER_C6_VILE_GAME_CTRL,
    MARKER_C7_YUMBLIE,
    MARKER_C8_MR_VILE, 
    MARKER_C9_FLOTSAM,

    MARKER_D4_SPRING_PAD = 0xD4,
    MARKER_D5_BGS_MUD_HUT,
    MARKER_D6_PINK_EGG_LARGE,
    MARKER_D7_PINK_EGG_MEDIUM,
    MARKER_D8_PINK_EGG_SMALL,
    MARKER_D9_PINK_EGG_SMALLEST,
    MARKER_DA_LEAFBOAT,
    MARKER_DB_BURIED_TREASURE,
    MARKER_DC_BIG_ALLIGATOR,
    MARKER_DD_BLACK_SNIPPET,
    MARKER_DE_BLACK_SNIPPET_UPSIDEDOWN,

    MARKER_EA_LIGHTHOUSE_DOOR = 0xEA,
    MARKER_EB_GV_BANJO_DOOR,
    MARKER_EC_GV_SUN_SWITCH,
    MARKER_ED_GV_SUN_DOOR,

    MARKER_EF_GV_STAR_HATCH = 0xEF,
    MARKER_F0_GV_KAZOOIE_DOOR,
    MARKER_F1_GV_STAR_SWITCH,
    MARKER_F2_HONEYCOMB_SWITCH,
    MARKER_F3_GV_KAZOOIE_TARGET,
    MARKER_F4_ANCIENT_ONE,
    MARKER_F5_BGS_ELEVATED_WALKWAY_SWITCH,
    MARKER_F6_LOCKUP_MEDIUM,
    MARKER_F7_LOCKUP_FAST,
    MARKER_F8_GV_KAZOOIE_DOOR,
    MARKER_F9_JINXY,

    MARKER_FC_CROCTUS = 0xFC,
    MARKER_FD_BGS_MAZE_SWITCH,
    MARKER_FE_MMM_CLOCK_SWITCH,

    MARKER_103_MM_WITCH_SWITCH = 0x103,
    MARKER_104_MMM_WITCH_SWITCH,
    MARKER_105_TTC_WITCH_SWITCH,
    MARKER_106_RBB_WITCH_SWITCH,

    MARKER_109_BREAKABLE_BRICK_WALL = 0x109,

    MARKER_11B_WATER_LEVEL_SWITCH_1 = 0x11B,
    MARKER_11C_WATER_LEVEL_SWITCH_2,
    MARKER_11D_WATER_LEVEL_SWITCH_3,

    MARKER_121_GLASS_EYE = 0x121,

    MARKER_124_BOGGY_1         = 0x124,

    MARKER_127_BAT = 0x127,
    MARKER_128_COLLYWOBBLE_A,
    MARKER_129_BAWL_A,
    MARKER_12A_TOPPER_A,
    MARKER_12B_ATTACK_TUTORIAL,

    MARKER_135_QUARRIE = 0x135,

    MARKER_161_GV_WITCH_SWITCH = 0x161,
    MARKER_162_BGS_WITCH_SWITCH,

    MARKER_166_CC_WITCH_SWITCH = 0x166,
    MARKER_167_SHARKFOOD_ISLAND,
    MARKER_168_ICE_KEY,
    MARKER_169_SNS_EGG,

    MARKER_16B_SNIPPET_UPSIDEDOWN = 0x16B,

    MARKER_173_CHUMP_FISH_2 = 0x173,
    MARKER_174_GAME_OVER = 0x174,

    MARKER_176_COPYRIGHT_OVERLAY = 0x176,
    MARKER_177_PRESS_START_OVERLAY,
    MARKER_178_NO_CONTROLLER_OVERLAY,

    MARKER_182_RBB_EGG_TOLL = 0x182,

    MARKER_185_MODEL_RUSTY_BUCKET_REAR_PROPELLER = 0x185,

    MARKER_191_ENGINE_ROOM_PROPELLOR_1 = 0x191,
    MARKER_192_ENGINE_ROOM_PROPELLOR_2,
    MARKER_193_ENGINE_ROOM_PROPELLOR_3,

    MARKER_19A_TIPTUP = 0x19A,
    MARKER_19B_CHOIR_TURTLE_YELLOW,
    MARKER_19C_CHOIR_TURTLE_CYAN,
    MARKER_19D_CHOIR_TURTLE_BLUE,
    MARKER_19E_CHOIR_TURTLE_RED,
    MARKER_19F_CHOIR_TURTLE_PINK,
    MARKER_1A0_CHOIR_TURTLE_PURPLE,
    MARKER_1A1_BOSS_BOOM_BOX_LARGEST,
    MARKER_1A2_BOSS_BOOM_BOX_LARGE,
    MARKER_1A3_BOSS_BOOM_BOX_MEDIUM ,
    MARKER_1A4_BOSS_BOOM_BOX_SMALL,

    MARKER_1A7_CLANKER_WHIPCRACK = 0x1A7,

    MARKER_1AE_ZUBBA = 0x1AE,

    MARKER_1B1_CCW_GOBI = 0x1B1,
    MARKER_1B2_CLUCKER_A,

    MARKER_1B4_EEYRIE_BABY = 0x1B4,
    MARKER_1B5_CATERPILLAR,

    MARKER_1B7_BOOM_BOX = 0x1B7,

    MARKER_1BB_NABNUT = 0x1BB,

    MARKER_1C5_WHIPCRACK = 0x1C5,

    MARKER_1CD_GV_MAZE_CTRL = 0x1CD,

    MARKER_1D0_CLUCKER_B = 0x1D0,
    MARKER_1D1_PORTRAIT_CHOMPA_B,

    MARKER_1D4_SANDYBUTT_PYRAMID =  0x1D4,
    MARKER_1D5_PALM_TREE,

    MARKER_1E1_FF_MINIGAME = 0x1E1,
    MARKER_1E2_GRUBLIN_HOOD,

    MARKER_1E5_GOLD_FEATHER_COLLECTIBLE = 0x1E5,
    MARKER_1E6_TOPPER_B,
    MARKER_1E7_BAWL_B,
    MARKER_1E8_COLLYWOBBLE_B,
    MARKER_1E9_MUMBO_COST_SIGN,
    MARKER_1EA_GRUNTLING_RED,

    MARKER_1F1_GRUNTLING_BLACK = 0x1F1,

    MARKER_1F4_TOOTS = 0x1F4,

    MARKER_1F9_SNARE_BEAR = 0x1F9,
    MARKER_1FA_POLAR_BEAR_CUB_BLUE,
    MARKER_1FB_POLAR_BEAR_CUB_GREEN,
    MARKER_1FC_POLAR_BEAR_CUB_RED,
    MARKER_1FD_BLUE_PRESENT_COLLECTIBLE,
    MARKER_1FE_GREEN_PRESENT_COLLECTIBLE,
    MARKER_1FF_RED_PRESENT_COLLECTIBLE,
    MARKER_200_TWINKLY_BLUE,
    MARKER_201_TWINKLY_GREEN,
    MARKER_202_TWINKLY_ORANGE,
    MARKER_203_TWINKLY_RED,

    MARKER_205_TWINKLY_MUNCHER = 0x205,

    MARKER_208_BLUE_PRESENT = 0x208,
    MARKER_209_GREEN_PRESENT,
    MARKER_20A_RED_PRESENT,
    MARKER_20B_WOZZA,
    MARKER_20C_WOZZAS_JIGGY,

    MARKER_20F_WOZZA_IN_CAVE = 0x20F,

    MARKER_217_BEE_SWARM = 0x217,
    MARKER_218_LIMBO,
    MARKER_219_MUMMUM,
    MARKER_21A_SEAMAN_GRUBLIN,

    MARKER_224_BREAKABLE_FLOOR_COBWEB = 0x224,
    MARKER_225_BREAKABLE_WALL_COBWEB,

    MARKER_22A_CCW_WITCH_SWITCH = 0x22A,
    MARKER_22B_FP_WITCH_SWITCH,

    MARKER_231_WARP_CAULDRON = 0x231,

    MARKER_23A_GV_SNS_CHAMBER_DOOR = 0x23A,
    MARKER_23B_GV_SNS_SARCOPHAGUS,
    MARKER_23C_GV_SNS_SWITCH,

    MARKER_23F_LAIR_FLIGHT_PAD_SWITCH = 0x23F,
    MARKER_240_LAIR_SWITCH_FLIGHT_PAD = 0x240,

    MARKER_244_DINGPOT = 0x244,
    MARKER_245_XMAS_TREE_EGG_TOLL = 0x245,

    MARKER_250_ICECUBE_A = 0x250,

    MARKER_252_LOGGO = 0x252,
    MARKER_253_SCARAB_BEETLE,
    MARKER_254_PORTRAIT_CHOMPA_A,
    MARKER_255_PORTRAIT_OF_GRUNTY,
    MARKER_256_FIRE_FX,
    MARKER_257_PORTRAIT_OF_BLACKEYE,
    MARKER_258_PORTRAIT_OF_TOWER,
    MARKER_259_PORTRAIT_OF_TREE_AND_MOON,
    MARKER_25A_PORTRAIT_OF_TEEHEE,
    MARKER_25B_PORTRAIT_OF_MINION,
    MARKER_25C_GRUNTY_SPELL_FIREBALL,

    MARKER_25E_GRUNTILDA_FINAL_BOSS = 0x25E,
    MARKER_25F_ICECUBE_B = 0x25F,

    MARKER_261_FIGHT_FLIGHT_PAD = 0x261,

    MARKER_276_STONE_JINJO = 0x276,

    MARKER_27A_JINJO_STATUE_BASE = 0x27A,
    MARKER_27B_BOSS_JINJO_ORANGE,
    MARKER_27C_BOSS_JINJO_GREEN,
    MARKER_27D_BOSS_JINJO_PINK,
    MARKER_27E_BOSS_JINJO_YELLOW,
    MARKER_27F_JINJONATOR_STATUE_BASE,

    MARKER_280_GRUNTY_SPELL_GREEN_ATTACK = 0x280,

    MARKER_284_GRUNTY_SPELL_BARRIER = 0x284,
    MARKER_285_JINJONATOR,

    MARKER_288_GRUNTY_SHADOW = 0x288,

    MARKER_295_GRUNTLING_BLUE = 0x295,
    MARKER_296_TEEHEE_PURPLE,
    MARKER_297_GIANT_GRAVESTONE,
    MARKER_298_MUMMUM_BALL,

    MARKER_29A_FF_PRIZE = 0x29A,

    MARKER_29D_ROCK_TRAPPING_GRUNTY = 0x29D
};

#endif
