#ifndef PARTICLE_H
#define PARTICLE_H

enum common_particle_e {
    COMMON_PARTICLE_1_EGG_HEAD = 1,
    COMMON_PARTICLE_2 = 2,
    COMMON_PARTICLE_3 = 3,
    COMMON_PARTICLE_4_EGG_ASS = 4,
    COMMON_PARTICLE_5 = 5,
    COMMON_PARTICLE_6 = 6,
    COMMON_PARTICLE_7 = 7,
    COMMON_PARTICLE_8_JIGGY_SHINE = 8,
    COMMON_PARTICLE_9 = 9,
    COMMON_PARTICLE_A = 10,
    COMMON_PARTICLE_B = 11,
    COMMON_PARTICLE_C = 12,
    COMMON_PARTICLE_D = 13,
    COMMON_PARTICLE_E = 14,
    COMMON_PARTICLE_F = 15,
    COMMON_PARTICLE_10 = 16,
    COMMON_PARTICLE_11 = 17
};

#endif
